services:
  - type: web
    name: coworking-mio
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    rootDir: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
